apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "server-hpa-8jjf"
  namespace: "app"
  labels:
    app: "server"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "server"
    apiVersion: "apps/v1"
  minReplicas: {{ .Values.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.autoscaler.maxReplicas }}
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: {{ .Values.autoscaler.targetCPUUtilization }}